### ISSUE TITLE
Make remote scripts chapter easier to understand

### ISSUE THREAD

**Issue by skaltman** [dcl-docs/workflow#10]
* Confusing if you include the brackets for things like `alias xr='ssh -Y [SUNet ID]@rice.stanford.edu'`
* The `%local` vs. `%rice` convention is confusing. Many people thought you should include the `%local` or `%rice` in the code
* Explain if you run `source` from Terminal or RStudio

**Comment by behrman** [comment]
I've just pushed a new version of [Workflow](https://dcl-workflow.stanford.edu/). Since it now has a general audience, I've simplified it and removed the hodgepodge of topics specific to the class, including this chapter.
