### ISSUE TITLE
edit workflow for raw data

### ISSUE THREAD

**Issue by skaltman** [dcl-docs/workflow#7]
Separate scripts download the raw data from the internet and write to data-raw.
cities_raw.R, cities_raw.csv, etc. 

add rule to makefile for csv.

**Comment by behrman** [comment]
It may be better to simply mention this in the reading, but remove downloading raw data in the challenge to keep it simple.

**Comment by behrman** [comment]
This is a good idea, but it would require reworking the project example. I think the simpler project example is fine.
