### ISSUE TITLE
Consider using RStudio file templates instead of snippets for R scripts

### ISSUE THREAD

**Issue by skaltman** [dcl-docs/workflow#9]
RStudio 1.3 supports file templates: [RStudio 1.3 preview](https://blog.rstudio.com/2020/03/17/rstudio-1-3-the-little-things/?mkt_tok=eyJpIjoiTVdRd01HTTRZak0yWlRJMCIsInQiOiJKYlh1ZkFERldRSDh5YW9qUjg4XC9CM3NVUVhPekdhSTZUdktWc3FtaCtiTmhpckVXZXFFbmFwekdlVzJPVCtGcTlLMGd0akhTSmlxUGgrVUdiRzRFRzluZ3lcL1YzZm5CWGE1YktsNnh6aXJJOFc1VEg0NDdhdUw1OWVDclphV1pTIn0%3D)

This might be easier than a snippet for the R script template

**Comment by behrman** [comment]
The rscript snippet illustrates how to use snippet variables. Snippets have an advantage over file templates of being quite platform independent.
